### ISSUE TITLE
Feature request: ipv4#wildcard_mask method

### ISSUE THREAD

**Issue by bwks** [Sija/ipaddress.cr#13]
Would you consider a PR to add a wildcard_mask method to an IPv4 address? I would be happy to submit.

**Comment by Sija** [comment]
Hi @bwks!

Could you describe please the intention behind this feature?

**Comment by bwks** [comment]
> 
> 
> Hi @bwks!
> 
> Could you describe please the intention behind this feature?

Wildcard masks are the inverse if a netmask and are used in Cisco ACL's to match IP addresses/networks. This would help in my use case as I often need to generate the wildcard mask for ACL rules based in the network address.

HTH, please let me if you would like me to expand some more.

**Comment by Sija** [comment]
I've never seen those before, thus TIL, thanks 🎉 
It seems like a rarely-used, but valuable addition :)
Please, go ahead with the PR, I'll be happy to merge it.

**Comment by bwks** [comment]
😅 this functionality is already implemented. See: `Prefix32#hostmask`
