### ISSUE TITLE
IP regexp matching

### ISSUE THREAD

**Issue by Nephos** [Sija/ipaddress.cr#2]
Hi !

Are you interested in writing some ugly / powerful regexp for ipv4 ?
I did not check for performances or anything (current light regexp + manual value check VS full regexp parsing) but I do like the idea ^^ 

```crystal
 REGEXP = /(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/
```

could become something like

```crystal
REGEXP = "(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
```

[I ŵrote it for this project in first place](https://github.com/Nephos/CrystalEmail/blob/master/src/CrystalEmail/rfc1123.cr)

PS: I like this project, good job 👍

**Comment by Sija** [comment]
Hi,

Sure, I'm interested in every more valid - even if ugly - regex that enhances correctness ;)
Efficiency optimizations I'll leave for further refactors when needed.

Check for correctness though is done in [`IPAddress::IPv4.valid?`](https://github.com/Sija/ipaddress.cr/blob/1524b00a7e2ce4a348cd501f3089ed10b3008ad2/src/ipaddress/ipv4.cr#L38) method, which is used in other places too so, changing the regex won't make a difference in this case.

Thanks for report thought!
