### ISSUE TITLE
includes?

### ISSUE THREAD

**Issue by MadBomber** [Sija/ipaddress.cr#6]
I'm looking at interesting shards - ones I would classify as fundamental.  As I was looking at the README documentation for this shard I like what I see.  The first thing that came to my mind was how can I use this library to determine if an IP is coming from a blacklist/whitelist network.

```
blacklist = IpAddress.parse "58.147.0.0/16"
ip = IpAddress.new "58.147.16.222"
blacklist.include?(ip)
```
I have not yet looked at your code.  I was just thinking that a method like `include?` would be something I'd like to use.

**Comment by Sija** [comment]
It works as you'd expect, see:

https://github.com/Sija/ipaddress.cr/blob/37d08ea02c86c3565f3787a02434560e9ed102ef/src/ipaddress/ipv4.cr#L740-L755
